// <auto-generated />
namespace MoneyChest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_datafilter_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_datafilter_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201804280709585_update_datafilter_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
