// <auto-generated />
namespace MoneyChest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class make_storage_required_in_record : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_storage_required_in_record));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221316025_make_storage_required_in_record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
