// <auto-generated />
namespace MoneyChest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class autoexecution_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(autoexecution_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "201906300926125_autoexecution_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
