//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyChest.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyChest.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is active.
        /// </summary>
        internal static string Category_IsActive {
            get {
                return ResourceManager.GetString("Category_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is inactive.
        /// </summary>
        internal static string Category_IsInactive {
            get {
                return ResourceManager.GetString("Category_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string Category_New {
            get {
                return ResourceManager.GetString("Category_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        internal static string Category_ParentCategory {
            get {
                return ResourceManager.GetString("Category_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Category_Plural {
            get {
                return ResourceManager.GetString("Category_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as active.
        /// </summary>
        internal static string Category_SetActive {
            get {
                return ResourceManager.GetString("Category_SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as inactive.
        /// </summary>
        internal static string Category_SetInactive {
            get {
                return ResourceManager.GetString("Category_SetInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category_Singular {
            get {
                return ResourceManager.GetString("Category_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Currencies_SelectedAreActive {
            get {
                return ResourceManager.GetString("Currencies_SelectedAreActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Currencies_SelectedAreInactive {
            get {
                return ResourceManager.GetString("Currencies_SelectedAreInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as active.
        /// </summary>
        internal static string Currencies_SetActive {
            get {
                return ResourceManager.GetString("Currencies_SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as main.
        /// </summary>
        internal static string Currencies_SetAsMain {
            get {
                return ResourceManager.GetString("Currencies_SetAsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as inactive.
        /// </summary>
        internal static string Currencies_SetInactive {
            get {
                return ResourceManager.GetString("Currencies_SetInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Currency_Code {
            get {
                return ResourceManager.GetString("Currency_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is active.
        /// </summary>
        internal static string Currency_IsActive {
            get {
                return ResourceManager.GetString("Currency_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is main.
        /// </summary>
        internal static string Currency_IsMain {
            get {
                return ResourceManager.GetString("Currency_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New currency.
        /// </summary>
        internal static string Currency_New {
            get {
                return ResourceManager.GetString("Currency_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currency_Plural {
            get {
                return ResourceManager.GetString("Currency_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency_Singular {
            get {
                return ResourceManager.GetString("Currency_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Currency_Symbol {
            get {
                return ResourceManager.GetString("Currency_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol alignment.
        /// </summary>
        internal static string CurrencySymbolAlignment_EnumName {
            get {
                return ResourceManager.GetString("CurrencySymbolAlignment_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left ($100).
        /// </summary>
        internal static string CurrencySymbolAlignment_Left {
            get {
                return ResourceManager.GetString("CurrencySymbolAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (100$).
        /// </summary>
        internal static string CurrencySymbolAlignment_Right {
            get {
                return ResourceManager.GetString("CurrencySymbolAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string General_Add {
            get {
                return ResourceManager.GetString("General_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string General_ConfirmPassword {
            get {
                return ResourceManager.GetString("General_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        internal static string General_ConfirmPasswordError {
            get {
                return ResourceManager.GetString("General_ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion confirmation.
        /// </summary>
        internal static string General_DeletionConfirmation {
            get {
                return ResourceManager.GetString("General_DeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} {1}?.
        /// </summary>
        internal static string General_DeletionConfirmationMessage {
            get {
                return ResourceManager.GetString("General_DeletionConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string General_Description {
            get {
                return ResourceManager.GetString("General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string General_Edit {
            get {
                return ResourceManager.GetString("General_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string General_Menu {
            get {
                return ResourceManager.GetString("General_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string General_None {
            get {
                return ResourceManager.GetString("General_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string General_Ok {
            get {
                return ResourceManager.GetString("General_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string General_Remark {
            get {
                return ResourceManager.GetString("General_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string General_SaveChangesConfirmation {
            get {
                return ResourceManager.GetString("General_SaveChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string General_SaveChangesConfirmationMessage {
            get {
                return ResourceManager.GetString("General_SaveChangesConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string General_SaveFailed {
            get {
                return ResourceManager.GetString("General_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some entries are invalid.
        /// </summary>
        internal static string General_SaveFailedMessage {
            get {
                return ResourceManager.GetString("General_SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_EnumName {
            get {
                return ResourceManager.GetString("Language_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string LoginWindow_Authorization {
            get {
                return ResourceManager.GetString("LoginWindow_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LoginWindow_Login {
            get {
                return ResourceManager.GetString("LoginWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginWindow_LoginFailed {
            get {
                return ResourceManager.GetString("LoginWindow_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please verify your Name and Password..
        /// </summary>
        internal static string LoginWindow_LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginWindow_LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginWindow_Register {
            get {
                return ResourceManager.GetString("LoginWindow_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string LoginWindow_Registration {
            get {
                return ResourceManager.GetString("LoginWindow_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed.
        /// </summary>
        internal static string LoginWindow_RegistrationFailed {
            get {
                return ResourceManager.GetString("LoginWindow_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the same Name already exists. Please enter other Name..
        /// </summary>
        internal static string LoginWindow_RegistrationFailedMessage {
            get {
                return ResourceManager.GetString("LoginWindow_RegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string MainManu_Calendar {
            get {
                return ResourceManager.GetString("MainManu_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string MainManu_Categories {
            get {
                return ResourceManager.GetString("MainManu_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string MainManu_Currencies {
            get {
                return ResourceManager.GetString("MainManu_Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string MainManu_Dashboard {
            get {
                return ResourceManager.GetString("MainManu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string MainManu_Debts {
            get {
                return ResourceManager.GetString("MainManu_Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string MainManu_Planning {
            get {
                return ResourceManager.GetString("MainManu_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MainManu_Reports {
            get {
                return ResourceManager.GetString("MainManu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainManu_Settings {
            get {
                return ResourceManager.GetString("MainManu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string MainManu_Storages {
            get {
                return ResourceManager.GetString("MainManu_Storages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string MainManu_Transactions {
            get {
                return ResourceManager.GetString("MainManu_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Storage_Hidden {
            get {
                return ResourceManager.GetString("Storage_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Storage_Plural {
            get {
                return ResourceManager.GetString("Storage_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Storage_Singular {
            get {
                return ResourceManager.GetString("Storage_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string Storage_Visible {
            get {
                return ResourceManager.GetString("Storage_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string StorageGroup_Plural {
            get {
                return ResourceManager.GetString("StorageGroup_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string StorageGroup_Singular {
            get {
                return ResourceManager.GetString("StorageGroup_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence (-).
        /// </summary>
        internal static string TransactionType_Expense {
            get {
                return ResourceManager.GetString("TransactionType_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income (+).
        /// </summary>
        internal static string TransactionType_Income {
            get {
                return ResourceManager.GetString("TransactionType_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TransactionType_Name {
            get {
                return ResourceManager.GetString("TransactionType_Name", resourceCulture);
            }
        }
    }
}
